import React, { useState } from 'react';
import SchemeCard from './SchemeCard';
import { motion } from 'framer-motion';
import { Filter, Copy, Check, Download } from 'lucide-react';

const ResultsSection = ({ schemes, generalAdvice, t, language }) => {
    const [filter, setFilter] = useState('All');
    const [copied, setCopied] = useState(false);

    const filteredSchemes = schemes.filter(scheme => {
        if (filter === 'All') return true;
        if (filter === 'Central') return scheme.type === 'Central';
        if (filter === 'State') return scheme.type === 'State';
        return scheme.categoryTags.includes(filter);
    });

    const categories = ['All', 'Central', 'State', ...new Set(schemes.flatMap(s => s.categoryTags))].slice(0, 8);

    const handleCopy = () => {
        const text = schemes.map(s => `${s.name} (${s.type}): ${s.description}`).join('\n\n');
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handlePrint = () => window.print();

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>
            {/* Results Header */}
            <div style={{
                display: 'flex', flexWrap: 'wrap',
                justifyContent: 'space-between', alignItems: 'center', gap: 16,
            }} className="print:hidden">
                <motion.div
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    style={{ display: 'flex', alignItems: 'baseline', gap: 12 }}
                >
                    <h2 style={{
                        fontFamily: 'var(--font-display)',
                        fontWeight: 300, fontSize: 28,
                        letterSpacing: '-0.02em', color: 'var(--color-carbon)',
                    }}>
                        {t?.recommendedSchemes || 'Recommended Schemes'}
                    </h2>
                    <span style={{ fontSize: 16, color: 'var(--color-pebble)', letterSpacing: '-0.01em' }}>
                        ({schemes.length})
                    </span>
                </motion.div>

                <div style={{ display: 'flex', gap: 8 }}>
                    <button
                        onClick={handlePrint}
                        className="btn-ghost"
                        style={{ padding: '8px 16px', fontSize: 13 }}
                    >
                        <Download size={14} />
                        {t?.print || 'Print'}
                    </button>
                    <button
                        onClick={handleCopy}
                        className="btn-ghost"
                        style={{ padding: '8px 16px', fontSize: 13 }}
                    >
                        {copied ? <Check size={14} color="var(--color-tangerine-tag)" /> : <Copy size={14} />}
                        {copied ? (t?.copied || 'Copied!') : (t?.copyAll || 'Copy All')}
                    </button>
                </div>
            </div>

            {/* Print header */}
            <div className="hidden print:block" style={{ textAlign: 'center', marginBottom: 32 }}>
                <h1 style={{ fontSize: 28, marginBottom: 8 }}>Government Scheme Recommendations</h1>
                <p style={{ color: '#666' }}>Generated by Scheme.AI</p>
            </div>

            {/* Filter Pills */}
            <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.15 }}
                style={{ display: 'flex', flexWrap: 'wrap', gap: 8, alignItems: 'center' }}
                className="print:hidden"
            >
                <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginRight: 4 }}>
                    <Filter size={13} color="var(--color-pebble)" />
                    <span style={{ fontSize: 12, color: 'var(--color-pebble)', letterSpacing: '-0.01em' }}>
                        {t?.filter || 'Filter'}
                    </span>
                </div>
                {categories.map(cat => (
                    <button
                        key={cat}
                        onClick={() => setFilter(cat)}
                        className={filter === cat ? 'btn-primary' : 'btn-ghost'}
                        style={{
                            padding: '6px 14px', fontSize: 12,
                            ...(filter === cat ? {} : { color: 'var(--color-stone)' }),
                        }}
                    >
                        {cat}
                    </button>
                ))}
            </motion.div>

            {/* Cards Grid */}
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.2 }}
                style={{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 280px), 1fr))',
                    gap: 16,
                    alignItems: 'start',
                }}
                className="print:!block print:space-y-4"
            >
                {filteredSchemes.map((scheme, index) => (
                    <SchemeCard
                        key={index}
                        scheme={scheme}
                        index={index}
                        t={t}
                        language={language}
                    />
                ))}
            </motion.div>

            {/* General Advice */}
            {generalAdvice && generalAdvice.length > 0 && (
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="card print:bg-white"
                    style={{
                        borderLeft: '3px solid var(--color-tangerine-tag)',
                        borderRadius: 'var(--radius-cards)',
                    }}
                >
                    <h3 style={{
                        fontFamily: 'var(--font-display)',
                        fontWeight: 400, fontSize: 18,
                        letterSpacing: '-0.02em', color: 'var(--color-carbon)',
                        marginBottom: 16,
                    }}>
                        {t?.advisorNotes || 'Advisor Notes'}
                    </h3>
                    <ul style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                        {generalAdvice.map((tip, idx) => (
                            <li key={idx} style={{
                                display: 'flex', gap: 10,
                                fontSize: 14, color: 'var(--color-stone)',
                                lineHeight: 1.6, letterSpacing: '-0.01em',
                            }}>
                                <span style={{ color: 'var(--color-tangerine-tag)', flexShrink: 0 }}>›</span>
                                {tip}
                            </li>
                        ))}
                    </ul>
                </motion.div>
            )}
        </div>
    );
};

export default ResultsSection;
